version: '3.8'

services:

  react-app:
    build: .
    ports:
      - "80:80"
      - "443:443"

    volumes:
      #     # Mount the Let's Encrypt directory from your host to the container
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount as read-only
