name: Deploy React App with Docker

on:
  push:
    branches:
      - prod  # Trigger deployment only on pushes to the prod branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub (or GitHub Container Registry if you prefer)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: SSH into the server
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Stop and remove any existing container
            docker-compose down

            # Start a new container using docker-compose
            docker-compose up --build -d
